apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-devops-app
  template:
    metadata:
      labels:
        app: python-devops-app
    spec:
      containers:
      - name: python-app-container
        image: yogithak/python-devops-app:12
        ports:
        - containerPort: 5000
