apiVersion: v1
kind: Service
metadata:
  name: python-devops-service
spec:
  type: NodePort
  selector:
    app: python-devops-automation-project
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30008
