apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-devops-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-devops-automation-project
  template:
    metadata:
      labels:
        app: python-devops-automation-project
    spec:
      containers:
      - name: python-app-container
        image: yogithak/python-devops-automation-project:16
        ports:
        - containerPort: 5000
